version: "3"

services:
  db:
    container_name: sentaku_db
    image: postgres:11.4-alpine

  app:
    container_name: sentaku_app
    build: .
    volumes:
      - .:/app_name
    ports:
      - 3001:3001
    depends_on:
      - db
